[build-system]
requires = [
    "setuptools>=61",
    "setuptools-rust>=1.6",
]
build-backend = "setuptools.build_meta"

[project]
name = "rational-linkages"
version = "3.0.0"
description = "Rational Linkages"
authors = [
    {name = "Daniel Huczala", email = "daniel.huczala@snu.ac.kr"},
]
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Operating System :: OS Independent",
]
dependencies = [
    "biquaternion-py >= 1.2.0",
    "numpy >= 2.0",
    "sympy >= 1.10.0",
    "PyQt6 >= 6.2.0",
    "pyqtgraph < 0.14",
    "PyOpenGL >= 3.0.0",
    "matplotlib >= 3.9.0; platform_system == 'Windows' and platform_machine == 'ARM64'", # Windows ARM has issues with PyQt6
]

[project.optional-dependencies]
opt = [
    "ipython >= 8.0.0",
    "scipy >= 1.10.0",
    "matplotlib >= 3.9.0",
]
cad = [
    "exudyn >= 1.9.0",
    "ngsolve >= 6.2.0",
    "build123d",
    "trimesh",
    "manifold3d",
]
doc = [
    "sphinx",
    "sphinx-rtd-theme",
    "nbsphinx",
    "sphinxcontrib-bibtex",
    "sphinx-copybutton",
    "sphinx-autodoc-typehints",
    "toml",
    "gitpython",
]
dev = [
    "build",
    "cibuildwheel",
    "twine",
    "pytest",
    "pytest-cov",
    "sybil",
    "ruff"
]

[project.urls]
Homepage = "https://git.uibk.ac.at/geometrie-vermessung/rational-linkages"
Documentation = "http://rational-linkages.readthedocs.io/"
Issues = "https://github.com/hucik14/rational-linkages/issues"

[tool.setuptools.packages.find]
where = ["python"]
include = ["rational_linkages*"]

[tool.setuptools.package-data]
"rational_linkages.data" = ["*.pkl", "*.stl"]

[[tool.setuptools-rust.ext-modules]]
target = "rational_linkages.utils_rust"
path = "rust/Cargo.toml"
binding = "PyO3"

[tool.cibuildwheel]
skip = "pp* cp3*t-*"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
environment = { CARGO_TERM_COLOR = "always" }
#test-command = "pytest {package}/python/tests"
test-command = ""
#test-skip = ["*-macosx_arm64", "*-macosx_x86_64"]

[tool.cibuildwheel.linux]
#archs = ["x86_64", "aarch64"]  # legacy option, now set by CIBW_ARCHS_LINUX in wheels.yml of GitHub Actions
environment = { PATH = "$HOME/.cargo/bin:$PATH", CARGO_TERM_COLOR = "always" }
before-build = "command -v cargo || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

[tool.cibuildwheel.windows]
archs = ["AMD64"]
#archs = ["ARM64"]

[tool.cibuildwheel.macos]
archs = ["arm64", "x86_64"]
environment = { MACOSX_DEPLOYMENT_TARGET = "11.0", CARGO_TERM_COLOR = "always" }

[tool.ruff]
src = ["python"]
line-length = 100
target-version = "py313"

[tool.pytest.ini_options]
addopts = "--cov=rational_linkages --cov-report=term-missing"
testpaths = ["python/tests"]
#testpaths = ["python/tests", "python/rational_linkages"]  # test all
# pytest -q python/tests/test_docs_examples.py  # set HEADLESS = False

[tool.coverage.report]
omit = [
    "*/test*",
    "*/__init__.py",
    "*/Plotter.py",
    "*/PlotterMatplotlib.py",
    "*/PlotterPyqtgraph.py",
    "*/MotionDesigner.py",
    "*/MotionApproximation.py",
    "*/StaticMechanism.py",
    "*/AffineMetric.py",
    "*/CollisionAnalyser.py",
    "*/MiniBall.py",
    "*/SingularityAnalysis.py",
]
