name: "🐞 Bug Report"
description: "Report an issue with the Python package"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "### Please fill in all the details below to help us troubleshoot the issue."

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Run `your_command_here`
        2. Observe error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: "Error Logs / Tracebacks"
      description: "Paste any error messages here."
      render: shell

  - type: input
    id: python_version
    attributes:
      label: "Python Version"
      description: "e.g., 3.8, 3.13, etc."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment Details"
      description: "Include dependency versions, installation method (pip/conda), OS, etc."
      placeholder: |
        - Python: 3.9
        - OS: macOS 13.0
        - Dependencies: pandas 1.5.0, numpy 1.24.0
    validations:
      required: false
