name: "🚀 Feature Request"
description: "Suggest an idea for the Python package"
title: "[Feature]: "
labels: ["feature request", "enhancement"]
body:
  - type: markdown
    attributes:
      value: "### Please describe the feature you would like to see."

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "What feature would you like to see added?"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: "Why is this feature useful? How would you use it?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Have you considered other approaches?"
    validations:
      required: false
