name: "❓ Question"
description: "Ask a general question related to the Python package"
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "What would you like to ask?"
    validations:
      required: true
